apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-gui
  name: mongo-gui
  namespace: demoProject
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30987
  selector:
    client: mongo-client