apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-ui
  name: mongo-ui-controller
  namespace: demoProject
spec:
  replicas: 1
  template:
    metadata:
      labels:
        client: mongo-client
    spec:
      volumes:
      - name: mongo-ui-data   
        emptyDir: {}
      containers:
      - image: mongoclient/mongoclient
        name: mongo-ui 
        ports:
        - name: mongo-ui
          containerPort: 3000
          hostPort: 3000
        volumeMounts:
            - name: mongo-ui-data
              mountPath: /data/mongo-ui