apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-gui
  name: mongo-gui-controller
  namespace: demoProject
spec:
  replicas: 1
  template:
    metadata:
      labels:
        client: mongo-client
    spec:
      volumes:
      - name: mongo-gui-data   
        emptyDir: {}
      containers:
      - image: webts/rockmongo
        name: mongo-gui
        ports:
        - name: mongo-gui
          containerPort: 80
          hostPort: 3333
        volumeMounts:
            - name: mongo-gui-data
              mountPath: /data/lxmongo-gui