apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-gui
  name: mongo-gui-controller
  namespace: demoProject
spec:
  replicas: 2
  template:
    metadata:
      labels:
        client: mongo-client
    spec:
      volumes:
      - name: mongo-gui-data   
        emptyDir: {}
      containers:
      - image: adicom/admin-mongo
        name: mongo-gui
        env: 
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3333"
        - name: PASSWORD
          value: "mongoGUI"   
        ports:
        - name: mongo-gui
          containerPort: 3333
          hostPort: 3333
        volumeMounts:
            - name: mongo-gui-data
              mountPath: /data/lxmongo-gui