apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
  namespace: demoProject
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30321
  selector:
    name: mongo